apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radar-immobilier-preprod
resources:
  - ../backup-common
configMapGenerator:
  - name: radar-pra-settings
    behavior: replace
    literals:
      - BACKUP_ENV=preprod
      - BACKUP_S3_BUCKET=radar-immobilier-backups-preprod
      - BACKUP_S3_ENDPOINT=https://s3.bhs.io.cloud.ovh.net
      - EXPECTED_DATABASE=radar
      - AWS_DEFAULT_REGION=bhs
