apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radar-object-storage-inventory-checkpoint
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: block-standard
  resources:
    requests:
      storage: 1Gi
