apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radar-immobilier-preprod

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: radar-immobilier
      app.kubernetes.io/part-of: sentropic

resources:
  - checkpoint-pvc.yaml
