apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: radar-immobilier-preprod

resources:
  - job.yaml

configMapGenerator:
  - name: radar-refresh-keyring-import-script
    files:
      - enroll-codex-import.mjs

generatorOptions:
  disableNameSuffixHash: true
