---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radar-pra-admin-prod
  namespace: radar-immobilier
spec:
  encryptedData:
    S3_ACCESS_KEY: AgB6GNOag5MNizPE9QNvAjcLhCdwEit71FD27R0VCToCQEEf0hXfKwk/IPUAwI7gK203s3sB8mfJlOqcGkctw1c1ZOXlTWG62Wz+viqOGyUm1xzvYQf1y+z2wFpzqaFn9QSxkqRh5SLyoEzisUExuLoXX6xaICtS/2uTVcuf4yoeFhElLPDBIUCMMyeGxBLJ0JWY2+18VhsMx6lijxn9ZdCFp0ozfvradmWpqcaRo10JY6wnkvTPaG1gkjagzdtzoXr8FO3+Ei7/cdfB7mwXwGeSb+oLFAx6SyLEqaKjwjcKS/kclz0dUTIABoK+FRpEAr9gaP6SOe5CNrFWLOz0j8ZhrikXx5Z34PSV2zWRRe/QKzVpyzsjq7kShKLXTAlu40c7ybbMZ83EzpHkCe+boLgWIaBoRz1FBomPocpx/faf072/MlNS8ybWMm8AFxrsfQDQK4mkZQrPLmKEPrKfS/CO13OhFw9PfFONFVusZjiq4R6+dxpMgcXaV+O/U+dw+j8jHyjxUgQGOMOk+KtZx7ugLzmQpVKEkmjfd+2yjUT9QZuepD2CuUGQfpG9ZAxqwSatrwik1OoLvLhXTn/vuHLI41UNHCguK9bKE8MXB+n3MEG2mgrFwnu8APzry6W88NW4G9lk+OWrt8TNE2LiEo4etGg/it1o0mb+eAUhWZ6HQFwd+P7spNF9jJ6vvhk64LIhfR6xowSXYWHXba0zzl6kmCU4FqEJcLfvuyCRLjWduw==
    S3_SECRET_KEY: AgAEWv8MineSTU5PsBxZlCO7vCc35unD5DjMXwjI4TGkkAUfLeL0OMtnlLIG2hrWF0bt7mxsfG8wNphX8GZxSLbnYbGEauSNejPA0FW2+odbbuUATaIZnMXTWmqn8V5koE/mPboKJeYGLlGDmAq+onGAPR6+YR4qQU3DTTr7h9vODmo86lyrLa4SjnQrNBwkr63LUl8DzxXNcY9ofUmcpLRnZFKiODxWEnOL2bTj/stXN3qPlVW46DYIg1r3ZhNT6R+VWoG2CE35zUV89+5P9zTFjWQSxsDe5zkZLz83duOgatU6OgDjJLRFaTOLBTMONKyF66A/aRs5j/Ea3kE7efU3zN7dL5HyPJVPK1hhSPDfE7tS/tChA22GfsjngmseJJsnmTwGeiHonM+zoDluSt3eFsGmdOY5TwVRTHF5zjkhmH3Wu5KtsCJXIdDqq4Qte/Ojd+5blt4myIMzKJVPz6iTYfKf+jonxoNiU+tESJhSnmt8ofFnpvDiJiRwOFLum7x4NkrTSO8hS/l3NimhlJyehTlmMJbRiFAWNriGzEt2pEKeqI+syz/vW2ec7v8wXf3R6+6Trx9g/yX9ztnsyP1H0N9mpyt/xyHx5DF8S/uwT8PvEKwMj6wHElvcHiVXkfqMhfCHBm+JqNTqxhyQB9P42P9K4vlBs6Lw3pn7a3bFOC+0wxpDdmL3rFeNcaxK4/GfzunbLG97vhdhxl0M63nOEN2sBAkjHx291WY8rLN/XA==
  template:
    metadata:
      name: radar-pra-admin-prod
      namespace: radar-immobilier
    type: Opaque
